# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e8f9e79eef0fd15a895c253753d2a460a848ed9ff3c658f0eb0f2e24b23e51ed40210fac0709fdab28a4c3c062dd7783046fcf470fe929c0662c01a839918ed

test:
  secret_key_base: b2afcc558380dc80c44bef34033b52239c529b0bcfa1d795e92c9c388b6abfd777342ecace9e548770e1d71d4add2183ecdd8e35f555327db56634bb1c53f24a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
